[application]

[web.app]

# HTML title tag content
title = "rimmich"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[bundle]
name = "rImmich"
identifier = "com.uploader.rimmich"
icon = ["assets/icon.png"]
resources = ["assets"]
publisher = "xufang"
